spring.application.name=springboot_practice

server.port=8432

#Active profile
spring.profiles.active=dev

#Banner off
#spring.main.banner-mode=off


#DB Integeration
spring.datasource.url=jdbc:mysql://localhost:3306/employee_management
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=Rashmi##2704@
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql:true





